### ISSUE TITLE
BugFix : create function not pass  options

### ISSUE THREAD

**Issue by js-seth-h** [alykoshin/nssm#1]
line 105 :  module.exports = function(options) { return new Nssm(options); };

should be fixed to

module.exports = function(name, options) { return new Nssm(name, options); };

please, apply patch.

**Comment by alykoshin** [comment]
Fixed, also added simple tests to avoid this in future.
Everything else is ok?

**Comment by alykoshin** [comment]
Assume issue is fixed.
